home/pom.xml, pom.xml, webapp/pom.xml
Resolves: https://jira.duraspace.org/browse/VIVO-1479
=> Change project version from 2.0.0-SNAPSHOT to 1.10.0-SNAPSHOT

webapp/src/main/webapp/templates/freemarker/visualization/mapOfScience/aboutMapOfScience_en_US.ftl
https://jira.duraspace.org/projects/VIVO/issues/VIVO-1490
=> Added missing period '.'

pom.xml
Updated maven-gpg-plugin location, nexus-staging-maven-plugin version, distributionManagement repository
=> Update pom.xml for 1.10 release

pom.xml
Reverts vivo-project/VIVO-languages#12
=> Revert "Update pom.xml for 1.10 release"

pom.xml
Created release-sign-artifacts profile, moved gpg plugin and release profile plugins to new profile
=> Update pom.xml - release-sign-artifacts profile

home/pom.xml, pom.xml, webapp/pom.xml
Sync master branch with rel-1.10-maint for 1.10.0 Release
=> Sync master branch with rel-1.10-maint for 1.10.0 Release

home/src/main/resources/rdf/display/everytime/menu_de_DE.n3
Bring in updates from: https://github.com/VIVO-DE/VIVO-languages
Related to: https://jira.duraspace.org/browse/VIVO-1661
=> Add capability map translation

de_DE/home/src/main/resources/rdf/tbox/everytime/initialTBoxAnnotations_de_DE.nt, de_DE/home/src/main/resources/rdf/tbox/firsttime/vitroAnnotations_de-DE.n3, de_DE/webapp/src/main/webapp/i18n/vivo_all_de_DE.properties
Copy of the latest version of all language related files.
https://jira.lyrasis.org/browse/VIVO-1769
=> Latest version of all German files

fr_CA/home/src/main/resources/rdf/tbox/filegraph/vivo_fr_CA.ttl
Resolves: https://jira.lyrasis.org/browse/VIVO-1772
=> Update minor typo in 'Prix et Distinction'

de_DE/home/src/main/resources/rdf/tbox/firsttime/vitroAnnotations_de-DE.n3
Fixed some syntax errors (in vivo:isCorrespondingAuthor, owl:sameAs, bibo:court, vivo:hasProceedings)
=> Fixed errors in vitroAnnotations_de-DE.n3

.gitignore, core/home/pom.xml, core/webapp/pom.xml
See https://github.com/vivo-project/Vitro/pull/160 for full details
* https://github.com/vivo-project/Vitro-languages/pull/18
* https://github.com/vivo-project/Vitro/pull/160
* https://github.com/vivo-project/VIVO/pull/168
Part of resolution to: https://jira.lyrasis.org/browse/VIVO-1836
=> Add language-specific modules into the core build artifact

fr_CA/webapp/src/main/webapp/i18n/vivo_all_fr_CA.properties
Fixes https://jira.lyrasis.org/browse/VIVO-1854
=> Removed typos in vivo_all_fr_CA.properties

fr_CA/home/src/main/resources/rdf/display/everytime/menu_fr_CA.ttl, fr_CA/home/src/main/resources/rdf/display/firsttime/PropertyConfig_fr_CA.ttl, fr_CA/home/src/main/resources/rdf/tbox/filegraph/vivo_fr_CA.ttl
Fixes https://jira.lyrasis.org/browse/VIVO-1876.
=> Fixed typos, whitespaces and mistranslations in fr_CA ttl files

fr_CA/home/src/main/resources/rdf/tbox/everytime/initialTBoxAnnotations_fr_CA.nt
https://github.com/vivo-project/VIVO/pull/170 fix is not working with the fr_CA version of VIVO, due to missing file (see [comment](https://github.com/vivo-project/VIVO/pull/170#issuecomment-631772400)).
This PR is adding the necessary folder and file.
=> Added initialTBoxAnnotations_fr_CA.nt

de_DE/webapp/src/main/webapp/i18n/vivo_all_de_DE.properties, en_CA/webapp/src/main/webapp/i18n/vivo_all_en_CA.properties, en_US/webapp/src/main/webapp/i18n/vivo_all_en_US.properties, es/webapp/src/main/webapp/i18n/vivo_all_es.properties, fr_CA/webapp/src/main/webapp/i18n/vivo_all_fr_CA.properties, pt_BR/webapp/src/main/webapp/i18n/vivo_all_pt_BR.properties
[VIVO-1844](https://jira.lyrasis.org/browse/VIVO-1844)
Relates to https://github.com/vivo-project/VIVO/pull/183
@VIVO-project/vivo-committers
=> [VIVO-1844] add translations for form headings

fr_CA/webapp/src/main/webapp/templates/freemarker/edit/forms/addConceptThroughObjectPropertyAutoComplete_fr_CA.ftl, fr_CA/webapp/src/main/webapp/templates/freemarker/edit/forms/defaultAddMissingIndividualForm_fr_CA.ftl
https://jira.lyrasis.org/browse/VIVO-1916
=> - added i18n in some freemarker templates in french language files

fr_CA/webapp/src/main/webapp/templates/freemarker/edit/forms/addRoleToPersonTwoStage_fr_CA.ftl
Addendum fix to https://jira.lyrasis.org/browse/VIVO-1842
This PR will allow to use single and double quotes in i18n property-files. 
In the fr_CA context, go to a person profile, then **Enseignement > Activités d'enseignement > Add** and make sure the mousover of the linguistic menu at the top of the page is working properly.
=> Added js_string method to addRoleToPersonTwoStage_fr_CA.ftl

fr_CA/home/src/main/resources/rdf/i18n/fr_CA/tbox/everytime/initialTBoxAnnotations_fr_CA.nt, fr_CA/home/src/main/resources/rdf/i18n/fr_CA/tbox/filegraph/vivo_fr_CA.ttl
Solves minor translation issues in https://jira.lyrasis.org/browse/VIVO-1809
=> Minor modifications in fr_CA RDF files

de_DE/webapp/src/main/webapp/i18n/vivo_all_de_DE.properties, en_CA/webapp/src/main/webapp/i18n/vivo_all_en_CA.properties, en_US/webapp/src/main/webapp/i18n/vivo_all_en_US.properties, es/webapp/src/main/webapp/i18n/vivo_all_es.properties, fr_CA/webapp/src/main/webapp/i18n/vivo_all_fr_CA.properties, pt_BR/webapp/src/main/webapp/i18n/vivo_all_pt_BR.properties
Required for https://github.com/vivo-project/VIVO/pull/207.
I welcome fixes for the strings, I just used Google Translate when I didn't already have a translation handy.
@sachaj @bkampe
=> [VIVO-1798] - Internationalize first and last name validation

core/home/pom.xml, core/pom.xml, core/webapp/pom.xml, de_DE/home/pom.xml, de_DE/pom.xml, de_DE/webapp/pom.xml, en_CA/home/pom.xml, en_CA/pom.xml, en_CA/webapp/pom.xml, en_US/home/pom.xml, en_US/pom.xml, en_US/webapp/pom.xml, es/home/pom.xml, es/pom.xml, es/webapp/pom.xml, fr_CA/home/pom.xml, fr_CA/pom.xml, fr_CA/webapp/pom.xml, pom.xml, pt_BR/home/pom.xml, pt_BR/pom.xml, pt_BR/webapp/pom.xml
https://jira.lyrasis.org/browse/VIVO-1999
Use with other three pull requests linked to JIRA issue.
Confirm that VIVO builds and runs normally.
=> Update version number in pom.xmls

core/home/pom.xml, core/pom.xml, core/webapp/pom.xml, de_DE/home/pom.xml, de_DE/pom.xml, de_DE/webapp/pom.xml, en_CA/home/pom.xml, en_CA/pom.xml, en_CA/webapp/pom.xml, en_US/home/pom.xml, en_US/pom.xml, en_US/webapp/pom.xml, es/home/pom.xml, es/pom.xml, es/webapp/pom.xml, fr_CA/home/pom.xml, fr_CA/pom.xml, fr_CA/webapp/pom.xml, pom.xml, pt_BR/home/pom.xml, pt_BR/pom.xml, pt_BR/webapp/pom.xml
Merge rel-1.12.0-maint to main
=> Merge rel-1.12.0-maint to main

core/home/pom.xml, core/pom.xml, core/webapp/pom.xml, de_DE/home/pom.xml, de_DE/pom.xml, de_DE/webapp/pom.xml, en_CA/home/pom.xml, en_CA/pom.xml, en_CA/webapp/pom.xml, en_US/home/pom.xml, en_US/pom.xml, en_US/webapp/pom.xml, es/home/pom.xml, es/pom.xml, es/webapp/pom.xml, fr_CA/home/pom.xml, fr_CA/pom.xml, fr_CA/webapp/pom.xml, pom.xml, pt_BR/home/pom.xml, pt_BR/pom.xml, pt_BR/webapp/pom.xml
=> rel 1.12.1 maint to main

de_DE/webapp/src/main/webapp/i18n/vivo_all_de_DE.properties
**Thank you for submitting a pull request! Title this pull request with a brief description of what the pull request fixes/improves/changes. Please describe the pull request in detail using the template below.**
* * *
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: (please link to issue)
* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
Removed a translation mistake in vivo_all_de_DE.properties
Improved german translation
Example:
region = Land/Bundesland/Bezirk
postal_code = Postleitzahl
A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the pull request does what is intended.
Any additional information that you think would be helpful when reviewing this PR.
Example:
* …
=> removed translation mistake

de_DE/webapp/src/main/webapp/i18n/vivo_all_de_DE.properties
=> Fixed typo

de_DE/webapp/src/main/webapp/i18n/vivo_all_de_DE.properties
Fixed literal translation to "faculty_of_1000 = Faculty-of-1000-Link"
=> Fixed translation for Faculty of 1000
